import type { StarlightSidebarTopicsUserOptions } from "starlight-sidebar-topics";
import type { StarlightIcon } from "@astrojs/starlight/types";

import starlightSidebarTopics from "starlight-sidebar-topics";

type Topic = {
  label: string;
  icon: StarlightIcon;
  link: string;
  items: (Autogenerated | Section | Page<string>)[];

  id?: string | undefined;
};

type Autogenerated = {
  autogenerate: { directory: string };
};

type Section = {
  label: string;
  items: (Autogenerated | Section | Page<string>)[];
};

type Page<T extends string> = {
  slug: Slug<T>;
};

type Slug<T extends string> = T extends `/${string}/`
  ? never
  : T extends `${string}/`
    ? never
    : T extends `/${string}`
      ? never
      : T;

// export const topic = (label: string, topic: Omit<Topic, "label">) => ({ label, ...topic }) as const;
// export const section = (label: string, section: Omit<Section, "label">) => ({ label, ...section });
// export const page = <T extends string>(slug: Slug<T>) => ({ slug });

export const topic = (
  {
    label,
    link,
    icon,
    id,
  }: {
    label: string;
    link: string;
    icon: StarlightIcon;
    id?: string;
  },
  ...sections: (Autogenerated | Section | Page<string>)[]
): Topic => ({ label, link, icon, id, items: sections });

export const autogenerate = {
  from: (template: TemplateStringsArray): Autogenerated => ({
    autogenerate: { directory: template[0]! },
  }),
} as const;

export const section =
  (template: TemplateStringsArray) =>
  (...pages: (Autogenerated | Section | Page<string>)[]): Section => ({
    label: template[0]!,
    items: pages,
  });

export const page = <T extends string>(template: TemplateStringsArray): Page<T> => {
  // https://github.com/microsoft/TypeScript/issues/33304
  let slug = template[0] as Slug<T>;

  if (slug.startsWith("/")) slug = slug.substring(1) as Slug<T>;
  if (slug.endsWith("/")) slug = slug.substring(0, slug.length - 1) as Slug<T>;

  return { slug };
};

export const sidebar = (options?: StarlightSidebarTopicsUserOptions, ...topics: Topic[]) =>
  starlightSidebarTopics(topics, options);
